language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3" ]; then composer require --no-update guzzlehttp/guzzle:~4.0; fi;'
  - composer install --prefer-source
